//
// Created by Per Lilja on 2020-09-17.
//

#ifndef RAYCASTINGINC_CONSTANTS_H
#define RAYCASTINGINC_CONSTANTS_H

#define FALSE 0
#define TRUE 1

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600

#define FPS 30
#define FRAME_TIME_LENGTH (1000 / FPS)

#endif //RAYCASTINGINC_CONSTANTS_H
